name: unit-tests

on:
  push:
    branches: [main, dev]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install bittensor
          pip install -e .

      - name: Run tests
        env:
          KMP_DUPLICATE_LIB_OK: "TRUE"
        run: pytest -q
